### ISSUE TITLE
Redundant Single-Line Functions in elements.ts

### ISSUE THREAD

**Issue by kiry5273** [8xEngineers/cse210-tinyfoot-team12#4]
In the `elements.ts` file, each function is created for a single line of code, which feels redundant and decreases readability. It forces developers to look up a separate file for functions that essentially perform very simple, one-line tasks. This not only makes the code harder to follow but also adds unnecessary complexity without providing significant benefit.
Should remove this file.

**Comment by hero1601** [comment]
I think we should remove this as its adding complexity for a single line of code
